In [420]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [421]:
df = pd.read_csv('../data/Advertising.csv')

In [422]:
df.head()

Unnamed: 0     TV  Radio  Newspaper  Sales
0           1  230.1   37.8       69.2   22.1
1           2   44.5   39.3       45.1   10.4
2           3   17.2   45.9       69.3    9.3
3           4  151.5   41.3       58.5   18.5
4           5  180.8   10.8       58.4   12.9

In [423]:
X = df.drop('Sales', axis=1)

y = df['Sales']

In [424]:
from sklearn.model_selection import train_test_split

In [425]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [426]:
from sklearn.preprocessing import StandardScaler

In [427]:
scaler = StandardScaler()

In [428]:
scaler.fit(X_train)

StandardScaler()

In [429]:
X_train = scaler.transform(X_train)

In [430]:
X_test = scaler.transform(X_test)

In [431]:
from sklearn.linear_model import Ridge

In [432]:
model = Ridge(alpha=100)

In [433]:
model.fit(X_train, y_train)

Ridge(alpha=100)

In [434]:
y_pred = model.predict(X_test)

In [435]:
from sklearn.metrics import mean_squared_error

In [436]:
mean_squared_error(y_test,y_pred)

7.3395051593079

In [437]:
model_2 = Ridge(alpha=1)

In [438]:
model_2.fit(X_train,y_train)

Ridge(alpha=1)

In [439]:
y_pred_2 = model_2.predict(X_test)

In [440]:
mean_squared_error(y_test, y_pred_2)

2.413580764141678

In [441]:
##################################################

In [442]:
X = df.drop('Sales',axis=1)

In [443]:
y = df['Sales']

In [444]:
X_train, X_other, y_train, y_other = train_test_split(X, y, test_size=0.3, random_state=101)

In [445]:
X_eval, X_test, y_eval, y_test = train_test_split(X_other, y_other, test_size=0.5, random_state=101)

In [446]:
len(df)

200

In [447]:
len(X_train)

140

In [448]:
len(X_eval)

30

In [449]:
len(X_test)

30

In [450]:
scaler = StandardScaler()
scaler.fit(X_train)

StandardScaler()

In [451]:
X_train = scaler.transform(X_train)

In [452]:
X_test = scaler.transform(X_test)

In [453]:
X_eval = scaler.transform(X_eval)

In [454]:
model_1 = Ridge(alpha=100)

In [455]:
model_1.fit(X_train,y_train)

Ridge(alpha=100)

In [456]:
y_eval_pred = model_1.predict(X_eval)

In [457]:
mean_squared_error(y_eval, y_eval_pred)

7.303724916324524

In [458]:
model_2 = Ridge(alpha=1)

In [459]:
model_2.fit(X_train,y_train)

Ridge(alpha=1)

In [460]:
y_eval_pred_2 = model_2.predict(X_eval)

In [461]:
mean_squared_error(y_eval,y_eval_pred_2)

2.4633571556229885

In [462]:
final_pred = model_2.predict(X_test)

In [463]:
mean_squared_error(y_test, final_pred)

2.363804372660367

In [464]:
#############################################

In [465]:
X = df.drop('Sales',axis=1)

In [466]:
y = df['Sales']

In [467]:
X_train, X_other, y_train, y_other = train_test_split(X, y, test_size=0.3, random_state=101)

In [468]:
scaler = StandardScaler()

In [469]:
scaler.fit(X_train)

StandardScaler()

In [470]:
X_train = scaler.transform(X_train)

In [471]:
X_test = scaler.transform(X_test)

In [472]:
model = Ridge(alpha=100)

In [473]:
from sklearn.model_selection import cross_val_score

In [474]:
scores = cross_val_score(model, X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [475]:
scores

array([ -9.46077895,  -4.99113998, -11.41979353,  -7.02510055,
        -8.4068186 ])

In [476]:
abs(scores.mean())

8.260726318542554

In [477]:
model = Ridge(alpha=1)

In [478]:
scores = cross_val_score(model, X_train,y_train,scoring='neg_mean_squared_error',cv=5)

In [479]:
scores

array([-3.23888218, -1.53762077, -5.34716477, -2.15662944, -4.51090513])

In [480]:
abs(scores.mean())

3.3582404599474787

In [481]:
model.fit(X_train,y_train)

Ridge(alpha=1)

In [482]:
y_final_predd = model.predict(X_test)

In [483]:
mean_squared_error(y_test,y_final_predd)

124.30012747537737

In [484]:
X = df.drop('Sales',axis=1)
y = df['Sales']

In [485]:
y

0      22.1
1      10.4
2       9.3
3      18.5
4      12.9
       ... 
195     7.6
196     9.7
197    12.8
198    25.5
199    13.4
Name: Sales, Length: 200, dtype: float64

In [486]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

In [487]:
scaler= StandardScaler()

In [488]:
scaler.fit(X_train)

StandardScaler()

In [489]:
X_train = scaler.transform(X_train)

In [490]:
X_test = scaler.transform(X_test)

In [491]:
from sklearn.model_selection import cross_validate

In [492]:
model = Ridge(alpha=100)

In [493]:
scores = cross_validate(model, X_train,y_train, scoring = ['neg_mean_squared_error','neg_mean_absolute_error' ], cv=10)

In [494]:
scores = pd.DataFrame(scores)

In [495]:
scores

fit_time  score_time  test_neg_mean_squared_error  \
0  0.001000    0.000000                    -6.090523   
1  0.000000    0.001000                   -10.766519   
2  0.001000    0.001001                    -4.037940   
3  0.001000    0.000000                    -5.030596   
4  0.000999    0.000000                    -9.145975   
5  0.000000    0.001000                   -13.129998   
6  0.001005    0.000997                    -3.838210   
7  0.004000    0.002002                    -9.060404   
8  0.000996    0.000000                    -9.164486   
9  0.001000    0.001000                    -5.748145   

   test_neg_mean_absolute_error  
0                     -1.808958  
1                     -2.507383  
2                     -1.484465  
3                     -1.876714  
4                     -2.516665  
5                     -2.467178  
6                     -1.451816  
7                     -2.360444  
8                     -2.439261  
9                     -1.890253

In [496]:
scores.mean()

fit_time                        0.001100
score_time                      0.000700
test_neg_mean_squared_error    -7.601280
test_neg_mean_absolute_error   -2.080314
dtype: float64

In [497]:
model = Ridge(alpha=1)

In [498]:
scores = cross_validate(model, X_train,y_train, scoring = ['neg_mean_squared_error','neg_mean_absolute_error' ], cv=10)

In [499]:
scores = pd.DataFrame(scores)

In [500]:
scores.mean()

fit_time                        0.001700
score_time                      0.001600
test_neg_mean_squared_error    -3.341985
test_neg_mean_absolute_error   -1.303906
dtype: float64

In [501]:
#################################################################


In [502]:
X = df.drop('Sales', axis=1)
y = df['Sales']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=101)

scaler = StandardScaler()
scaler.fit(X_train)

X_train = scaler.transform(X_train)
X_test = scaler.transform(X_test)

In [503]:
from sklearn.linear_model import ElasticNet

In [504]:
elastic_net = ElasticNet()

In [505]:
params = {'alpha':[0.1,1,5,10,50,100], 'l1_ratio':[.1,.5,.7,.95,.99,1]}

In [506]:
from sklearn.model_selection import GridSearchCV

In [507]:
grid_model = GridSearchCV(estimator=elastic_net, param_grid=params, scoring='neg_mean_squared_error', cv=5, verbose=2)

In [508]:
grid_model.fit(X_train,y_train)

Fitting 5 folds for each of 36 candidates, totalling 180 fits
[CV] alpha=0.1, l1_ratio=0.1 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.1, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.1 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.1, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.1 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.1, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.1 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.1, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.1 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.1, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.5 .........................................
[CV] .......................... alpha=0.1, l1_ratio=0.5, total=   0.0s
[CV] alpha=0.1, l1_ratio=0.5 .........................................
[CV] ..........

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ............................ alpha=5, l1_ratio=0.5, total=   0.0s
[CV] alpha=5, l1_ratio=0.5 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.5, total=   0.0s
[CV] alpha=5, l1_ratio=0.7 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.7, total=   0.0s
[CV] alpha=5, l1_ratio=0.7 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.7, total=   0.0s
[CV] alpha=5, l1_ratio=0.7 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.7, total=   0.0s
[CV] alpha=5, l1_ratio=0.7 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.7, total=   0.0s
[CV] alpha=5, l1_ratio=0.7 ...........................................
[CV] ............................ alpha=5, l1_ratio=0.7, total=   0.0s
[CV] alpha=5, l1_ratio=0.95 ..........................................
[CV] .

[Parallel(n_jobs=1)]: Done 180 out of 180 | elapsed:    0.4s finished


GridSearchCV(cv=5, estimator=ElasticNet(),
             param_grid={'alpha': [0.1, 1, 5, 10, 50, 100],
                         'l1_ratio': [0.1, 0.5, 0.7, 0.95, 0.99, 1]},
             scoring='neg_mean_squared_error', verbose=2)

In [509]:
grid_model.best_estimator_

ElasticNet(alpha=0.1, l1_ratio=1)

In [510]:
grid_model.best_params_

{'alpha': 0.1, 'l1_ratio': 1}

In [511]:
y_pred = grid_model.predict(X_test)
y_pred

array([15.71096589, 19.46333586, 11.59886257, 16.90630141,  9.31698537,
        7.18661984, 20.1749801 , 17.24661433,  9.88966295, 19.04951924,
       12.36445763, 13.90433551, 13.71688246, 21.11393415, 18.27872733,
       10.03488221, 15.63668441,  7.95351093,  7.68038303, 20.28322178,
        7.88858754, 18.06777354, 24.31854168, 22.62012891,  8.18850732,
       12.78855232, 21.33524558,  8.20859824, 12.42702099, 12.60102033,
       10.92776259, 19.08133337, 10.21982291,  6.98563573, 17.27886263,
        8.03884303,  9.38033208,  8.37439061, 10.59329275, 10.69579932,
       13.11514387,  9.85387447, 10.29814632,  8.18896299, 11.64305948,
       10.26419462,  9.12534879, 16.28155142, 13.39292296, 20.69005782,
       12.60009322, 14.06269567, 17.5149981 , 11.17829946, 12.73520647,
        5.6911742 , 23.08589128, 12.53657769, 18.72980041, 15.22206746])

In [512]:
from sklearn.metrics import mean_squared_error

In [513]:
mean_squared_error(y_test,y_pred)

2.4118830695088103